export enum ChildUpdatePropagationPermissivenessType {
  UpdatePermissiveness,
  InstanceUpdatePermissiveness,
  BuildPermissiveness,
  ChildUpdatePropagationPermissiveness,
  ChildrenMustBeEditionsPermissiveness,
  BuilderMustBeHolderPermissiveness,
  StakingPermissiveness,
  Namespaces,
  EquipItemPermissiveness,
  AddItemPermissiveness,
  UseItemPermissiveness,
  BasicStatTemplates,
  DefaultCategory,
  BodyParts,
  StatsUri,
}
