name: Pull Request

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal

      - name: Install Solana
        run: curl -sSfL https://release.solana.com/stable/install | sh
        shell: bash

      - name: Install AVM and Anchor Version 0.24.2
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/coral-xyz/anchor avm --locked --force --tag v0.24.2

      - name: Build Raindrops Programs
        run: anchor build --skip-lint
        working-directory: ./rust
