name: Pull Request

on:
  push:
    branches: '**'

env:
  ANCHOR_VERSION: 0.24.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/coral-xyz/anchor avm --locked --force 
      #- run: avm install $ANCHOR_VERSION
      #- run: anchor build
      #  working-directory: ./rust
