name: Pull Request

defaults:
  run:
    working-directory: ./rust

on:
  pull_request:
  push:
    branches: [master]

jobs:
  all_github_action_checks:
    runs-on: ubuntu-latest
    needs:
      - rustfmt
      - clippy
      - cargo-build-test
    steps:
      - run: echo "Done"
        working-directory: ./
