name: Pull Request

on:
  push:
    branches: '**'

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal 
      
      - name: Clippy
        uses: actions-rs/cargo@v1
        working-directory: ./rust
        with:
          command: clippy
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal 
      
      - name: Check Format
        uses: actions-rs/cargo@v1
        working-directory: ./rust
        with:
          command: fmt
          args: --all -- --check
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal

      - name: Install Solana
        run: curl -sSfL https://release.solana.com/stable/install | sh
        shell: bash

      - name: Install AVM
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/coral-xyz/anchor avm --locked --force --tag v0.24.2
      
      - name: Set Anchor
        run: avm use 0.24.2

      - name: Build Raindrops Programs
        run: anchor build --skip-lint
        working-directory: ./rust
