name: Pull Request

on:
  push:
    branches: '**'

defaults:
  run:
    shell: bash

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable 
          profile: minimal
          components: clippy
 
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path rust/Cargo.toml

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable 
          profile: minimal 
      
      - name: Check Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path rust/Cargo.toml --all -- --check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable 
          profile: minimal

      - name: Install Solana
        run: curl -sSfL https://release.solana.com/stable/install | sh
      
      - name: Install Anchor Dependencies
        run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install -y pkg-config build-essential libudev-dev
      
      - name: Install Anchor 0.24.2
        run: npm i -g @project-serum/anchor-cli@0.24.2

      - name: Build Raindrops Programs
        run: anchor build --skip-lint
        working-directory: ./rust
  
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check CLI
        uses: creyD/prettier_action@v4.2
        with:
          dry: true
          prettier_options: --check js/cli/src

      - name: Check Lib
        uses: creyD/prettier_action@v4.2
        with:
          dry: true
          prettier_options: --check js/lib/src
